use_frameworks!

platform :ios, '13.0'

target 'GPSSecurity_Example' do
  pod 'GPSSecurity', :path => '../'
  pod 'KeychainSwift', '~> 19.0'

  target 'GPSSecurity_Tests' do
    inherit! :search_paths
  end

end
